steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/cook-app-444212/cookapp1212', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/cook-app-444212/cookapp1212']

images:
- 'gcr.io/cook-app-444212/cookapp1212'
