"""empty message

Revision ID: 4784560e52c6
Revises: eda0835b6072
Create Date: 2024-12-01 22:43:57.295989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4784560e52c6'
down_revision = 'eda0835b6072'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_images', sa.Column('point', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_images', 'point')
    # ### end Alembic commands ###
