"""empty message

Revision ID: 48188822f6b1
Revises: 76886eebd251
Create Date: 2024-12-01 21:52:43.147170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48188822f6b1'
down_revision = '76886eebd251'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_images', sa.Column('point', sa.DateTime(), nullable=True))
    op.drop_column('user_images', 'meal_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_images', sa.Column('meal_type', sa.VARCHAR(length=20), nullable=True))
    op.drop_column('user_images', 'point')
    # ### end Alembic commands ###
