"""empty message

Revision ID: 76886eebd251
Revises: 2732ec06e6e8
Create Date: 2024-12-01 20:06:53.667823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76886eebd251'
down_revision = '2732ec06e6e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_missions', sa.Column('morning_points_awarded', sa.Boolean(), nullable=True))
    op.add_column('daily_missions', sa.Column('noon_points_awarded', sa.Boolean(), nullable=True))
    op.add_column('daily_missions', sa.Column('night_points_awarded', sa.Boolean(), nullable=True))
    op.add_column('user_images', sa.Column('meal_type', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_images', 'meal_type')
    op.drop_column('daily_missions', 'night_points_awarded')
    op.drop_column('daily_missions', 'noon_points_awarded')
    op.drop_column('daily_missions', 'morning_points_awarded')
    # ### end Alembic commands ###
