"""empty message

Revision ID: 7f5a8a20850e
Revises: 4784560e52c6
Create Date: 2024-12-02 11:17:13.176663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f5a8a20850e'
down_revision = '4784560e52c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dailymission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('breakfast', sa.Boolean(), nullable=True),
    sa.Column('lunch', sa.Boolean(), nullable=True),
    sa.Column('dinner', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dailymission')
    # ### end Alembic commands ###
