"""empty message

Revision ID: eda0835b6072
Revises: 48188822f6b1
Create Date: 2024-12-01 22:35:18.098474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eda0835b6072'
down_revision = '48188822f6b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('missions')
    op.drop_table('cat_progress')
    op.drop_table('daily_missions')
    op.drop_column('user_images', 'point')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_images', sa.Column('point', sa.DATETIME(), nullable=True))
    op.create_table('daily_missions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('morning_detected', sa.BOOLEAN(), nullable=True),
    sa.Column('noon_detected', sa.BOOLEAN(), nullable=True),
    sa.Column('night_detected', sa.BOOLEAN(), nullable=True),
    sa.Column('points_awarded', sa.INTEGER(), nullable=True),
    sa.Column('morning_points_awarded', sa.BOOLEAN(), nullable=True),
    sa.Column('noon_points_awarded', sa.BOOLEAN(), nullable=True),
    sa.Column('night_points_awarded', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cat_progress',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('level', sa.INTEGER(), nullable=True),
    sa.Column('total_points', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('missions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.VARCHAR(length=200), nullable=False),
    sa.Column('reward', sa.VARCHAR(length=100), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
