
tag_info = {
        'rice': {'category': '和食', 'japanese': 'ご飯', 'calories': 250},
        'eels on rice': {'category': '和食', 'japanese': 'うな重', 'calories': 400},
        'pilaf': {'category': '洋食', 'japanese': 'ピラフ', 'calories': 241},
        'chicken-n-egg on rice': {'category': '和食', 'japanese': '親子丼', 'calories': 631},
        'pork cutlet on rice': {'category': '和食', 'japanese': 'カツ丼', 'calories': 866},
        'beef curry': {'category': '洋食', 'japanese': 'ビーフカレー', 'calories': 771},
        'sushi': {'category': '和食', 'japanese': '寿司', 'calories': 561},
        'chicken rice': {'category': '和食', 'japanese': 'チキンライス', 'calories': 527},
        'fried rice': {'category': '和食', 'japanese': 'チャーハン', 'calories': 646},
        'tempura bowl': {'category': '和食', 'japanese': '天丼', 'calories': 616},
        'bibimbap': {'category': '中華', 'japanese': 'ビビンバ', 'calories': 551},
        'toast': {'category': '洋食', 'japanese': 'トースト', 'calories': 219},
        'croissant': {'category': '洋食', 'japanese': 'クロワッサン', 'calories': 175},
        'roll bread': {'category': '洋食', 'japanese': 'ロールパン', 'calories': 93},
        'raisin bread': {'category': '洋食', 'japanese': 'レーズンパン', 'calories': 158},
        'chip butty': {'category': '洋食', 'japanese': 'クリスプサンドイッチ', 'calories': 304},
        'hamburger': {'category': '洋食', 'japanese': 'ハンバーガー', 'calories': 494},
        'pizza': {'category': '洋食', 'japanese': 'ピザ', 'calories': 637},
        'sandwiches': {'category': '洋食', 'japanese': 'サンドイッチ', 'calories': 304},
        'udon noodle': {'category': '和食', 'japanese': 'うどん', 'calories': 219},
        'tempura udon': {'category': '和食', 'japanese': '天ぷらうどん', 'calories': 370},
        'soba noodle': {'category': '和食', 'japanese': 'そば', 'calories': 294},
        'ramen noodle': {'category': '中華', 'japanese': 'ラーメン', 'calories': 403},
        'beef noodle': {'category': '中華', 'japanese': '牛肉麺', 'calories': 700},
        'tensin noodle': {'category': '中華', 'japanese': '天津麺', 'calories': 860},
        'fried noodle': {'category': '中華', 'japanese': '焼きそば', 'calories': 441},
        'spaghetti': {'category': '洋食', 'japanese': 'スパゲッティ', 'calories': 375},
        'Japanese-style pancake': {'category': '和食', 'japanese': 'お好み焼き', 'calories': 517},
        'takoyaki': {'category': '和食', 'japanese': 'たこ焼き', 'calories': 300},
        'gratin': {'category': '洋食', 'japanese': 'グラタン', 'calories': 256},
        'sauteed vegetables': {'category': '和食', 'japanese': '野菜炒め', 'calories': 114},
        'croquette': {'category': '洋食', 'japanese': 'コロッケ', 'calories': 140},
        'grilled eggplant': {'category': '和食', 'japanese': '焼きナス', 'calories': 22},
        'sauteed spinach': {'category': '和食', 'japanese': 'ほうれん草のソテー', 'calories': 44},
        'vegetable tempura': {'category': '和食', 'japanese': '野菜天ぷら', 'calories': 99},
        'miso soup': {'category': '和食', 'japanese': '味噌汁', 'calories': 37},
        'potage': {'category': '洋食', 'japanese': 'ポタージュ', 'calories': 90},
        'sausage': {'category': '洋食', 'japanese': 'ソーセージ', 'calories': 54},
        'oden': {'category': '和食', 'japanese': 'おでん', 'calories': 590},
        'omelet': {'category': '洋食', 'japanese': 'オムレツ', 'calories': 309},
        'ganmodoki': {'category': '和食', 'japanese': 'がんもどき', 'calories': 85},
        'jiaozi': {'category': '中華', 'japanese': '餃子', 'calories': 251},
        'stew': {'category': '洋食', 'japanese': 'シチュー', 'calories': 239},
        'teriyaki grilled fish': {'category': '和食', 'japanese': '魚の照り焼き', 'calories': 287},
        'fried fish': {'category': '和食', 'japanese': '魚のフライ', 'calories': 49},
        'grilled salmon': {'category': '和食', 'japanese': '焼き鮭', 'calories': 101},
        'salmon meuniere': {'category': '洋食', 'japanese': '鮭のムニエル', 'calories': 210},
        'sashimi': {'category': '和食', 'japanese': '刺身', 'calories': 802},
        'grilled pacific saury': {'category': '和食', 'japanese': 'さんまの塩焼き', 'calories': 198},
        'sukiyaki': {'category': '和食', 'japanese': 'すき焼き', 'calories': 454},
        'sweet and sour pork': {'category': '中華', 'japanese': '酢豚', 'calories': 227},
        'lightly roasted fish': {'category': '和食', 'japanese': '焼き魚', 'calories': 76},
        'steamed egg hotchpotch': {'category': '和食', 'japanese': '茶碗蒸し', 'calories': 132},
        'tempura': {'category': '和食', 'japanese': '天ぷら', 'calories': 123},
        'fried chicken': {'category': '洋食', 'japanese': '唐揚げ', 'calories': 289},
        'sirloin cutlet': {'category': '洋食', 'japanese': 'ヒレカツ', 'calories': 248},
        'nanbanzuke': {'category': '和食', 'japanese': '南蛮漬け', 'calories': 178},
        'boiled fish': {'category': '和食', 'japanese': '煮魚', 'calories': 129},
        'seasoned beef with potatoes': {'category': '洋食', 'japanese': '肉じゃが', 'calories': 155},
        'hambarg steak': {'category': '洋食', 'japanese': 'ハンバーグステーキ', 'calories': 400},
        'beef steak': {'category': '洋食', 'japanese': 'ハンバーグ', 'calories': 268},
        'dried fish': {'category': '和食', 'japanese': '干物', 'calories': 243},
        'ginger pork saute': {'category': '和食', 'japanese': '生姜焼き', 'calories': 357},
        'spicy chili-flavored tofu': {'category': '中華', 'japanese': '麻婆豆腐', 'calories': 354},
        'yakitori': {'category': '和食', 'japanese': '焼き鳥', 'calories': 188},
        'cabbage roll': {'category': '洋食', 'japanese': 'ロールキャベツ', 'calories': 165},
        'rolled omelet': {'category': '和食', 'japanese': 'だし巻き卵', 'calories': 87},
        'grilled pork': {'category': '洋食', 'japanese': '豚のグリル', 'calories': 314},
        'spaghetti bolognese': {'category': '洋食', 'japanese': 'ボロネーゼ', 'calories': 408},
    }
