
tag_info = {
    'rice': {'japanese': 'ご飯', 'calories': 250},
    'eels on rice': {'japanese': 'うな重', 'calories': 400},
    'pilaf': {'japanese': 'ピラフ', 'calories': 241},
    'chicken-n-egg on rice': {'japanese': '親子丼', 'calories': 631},
    'pork cutlet on rice': {'japanese': 'カツ丼', 'calories': 866},
    'beef curry': {'japanese': 'ビーフカレー', 'calories': 771},
    'sushi': {'japanese': '寿司', 'calories': 561},
    'chicken rice': {'japanese': 'チキンライス', 'calories': 527},
    'fried rice': {'japanese': 'チャーハン', 'calories': 646},
    'tempura bowl': {'japanese': '天丼', 'calories': 616},
    'bibimbap': {'japanese': 'ビビンバ', 'calories': 551},
    'toast': {'japanese': 'トースト', 'calories': 219},
    'croissant': {'japanese': 'クロワッサン', 'calories':175 },
    'roll bread': {'japanese': 'ロールパン', 'calories': 93},
    'raisin bread': {'japanese': 'レーズンパン', 'calories': 158},
    'chip butty': {'japanese': 'クリスプサンドイッチ', 'calories': 304},
    'hamburger': {'japanese': 'ハンバーガー', 'calories': 494},
    'pizza': {'japanese': 'ピザ', 'calories': 637},
    'sandwiches': {'japanese': 'サンドイッチ', 'calories': 304},
    'udon noodle': {'japanese': 'うどん', 'calories': 219},
    'tempura udon': {'japanese': '天ぷらうどん', 'calories': 370},
    'soba noodle': {'japanese': 'そば', 'calories': 294},
    'ramen noodle': {'japanese': 'ラーメン', 'calories': 403},
    'beef noodle': {'japanese': '牛肉麺', 'calories': 700},
    'tensin noodle': {'japanese': '天津麺', 'calories': 860},
    'fried noodle': {'japanese': '焼きそば', 'calories': 441},
    'spaghetti': {'japanese': 'スパゲッティ', 'calories': 375},
    'Japanese-style pancake': {'japanese': 'お好み焼き', 'calories': 517},
    'takoyaki': {'japanese': 'たこ焼き', 'calories': 300},
    'gratin': {'japanese': 'グラタン', 'calories': 256},
    'sauteed vegetables': {'japanese': '野菜炒め', 'calories': 114},
    'croquette': {'japanese': 'コロッケ', 'calories': 140},
    'grilled eggplant': {'japanese': '焼きナス', 'calories': 22},
    'sauteed spinach': {'japanese': 'ほうれん草のソテー', 'calories': 44},
    'vegetable tempura': {'japanese': '野菜天ぷら', 'calories': 99},
    'miso soup': {'japanese': '味噌汁', 'calories': 37},
    'potage': {'japanese': 'ポタージュ', 'calories': 90},
    'sausage': {'japanese': 'ソーセージ', 'calories': 54},
    'oden': {'japanese': 'おでん', 'calories': 590},
    'omelet': {'japanese': 'オムレツ', 'calories': 309},
    'ganmodoki': {'japanese': 'がんもどき', 'calories': 85},
    'jiaozi': {'japanese': '餃子', 'calories': 251},
    'stew': {'japanese': 'シチュー', 'calories': 239},
    'teriyaki grilled fish': {'japanese': '魚の照り焼き', 'calories': 287},
    'fried fish': {'japanese': '魚のフライ', 'calories': 49},
    'grilled salmon': {'japanese': '焼き鮭', 'calories': 101},
    'salmon meuniere': {'japanese': '鮭のムニエル', 'calories': 210},
    'sashimi': {'japanese': '刺身', 'calories': 802},
    'grilled pacific saury': {'japanese': 'さんまの塩焼き', 'calories': 198},
    'sukiyaki': {'japanese': 'すき焼き', 'calories': 454},
    'sweet and sour pork': {'japanese': '酢豚', 'calories': 227},
    'lightly roasted fish': {'japanese': '焼き魚', 'calories': 76},
    'steamed egg hotchpotch': {'japanese': '茶碗蒸し', 'calories': 132},
    'tempura': {'japanese': '天ぷら', 'calories': 123},
    'fried chicken': {'japanese': '唐揚げ', 'calories': 289},
    'sirloin cutlet': {'japanese': 'ヒレカツ', 'calories': 248},
    'nanbanzuke': {'japanese': '南蛮漬け', 'calories': 178},
    'boiled fish': {'japanese': '煮魚', 'calories': 129},
    'seasoned beef with potatoes': {'japanese': '肉じゃが', 'calories': 155},
    'hambarg steak': {'japanese': 'ハンバーグステーキ', 'calories': 400},
    'beef steak': {'japanese': 'ハンバーグ', 'calories': 268},
    'dried fish': {'japanese': '干物', 'calories': 243},
    'ginger pork saute': {'japanese': '生姜焼き', 'calories': 357},
    'spicy chili-flavored tofu': {'japanese': '麻婆豆腐', 'calories': 354},
    'yakitori': {'japanese': '焼き鳥', 'calories': 188},
    'cabbage roll': {'japanese': 'ロールキャベツ', 'calories': 165},
    'rolled omelet': {'japanese': 'だし巻き卵', 'calories': 86},
    'egg sunny-side up': {'japanese': '目玉焼き', 'calories': 110},
    'fermented soybeans': {'japanese': '納豆', 'calories': 92},
    'cold tofu': {'japanese': '冷奴', 'calories': 197},
    'egg roll': {'japanese': '卵焼き', 'calories': 283},
    'chilled noodle': {'japanese': '冷やし中華', 'calories': 556},
    'stir-fried beef and peppers': {'japanese': 'チンジャオロース', 'calories': 288},
    'simmered pork': {'japanese': '豚の角煮', 'calories': 577},
    'boiled chicken and vegetables': {'japanese': '鶏肉と野菜の煮物', 'calories': 189},
    'sashimi bowl': {'japanese': '海鮮丼', 'calories': 720},
    'sushi bowl': {'japanese': 'ちらし寿司', 'calories': 654},
    'fish-shaped pancake with bean jam': {'japanese': 'たい焼き', 'calories': 213},
    'shrimp with chill source': {'japanese': 'エビチリ', 'calories': 203},
    'roast chicken': {'japanese': 'ローストチキン', 'calories': 273},
    'steamed meat dumpling': {'japanese': 'シュウマイ', 'calories': 46},
    'omelet with fried rice': {'japanese': 'オムライス', 'calories': 767},
    'cutlet curry': {'japanese': 'カツカレー', 'calories': 1023},
    'spaghetti meat sauce': {'japanese': 'ミートソーススパゲティ', 'calories': 606},
    'fried shrimp': {'japanese': 'エビフライ', 'calories': 149},
    'potato salad': {'japanese': 'ポテトサラダ', 'calories': 99},
    'green salad': {'japanese': '野菜サラダ', 'calories': 21},
    'macaroni salad': {'japanese': 'マカロニサラダ', 'calories': 203},
    'pork miso soup': {'japanese': '豚汁', 'calories': 116},
    'chinese soup': {'japanese': '中華スープ', 'calories': 47},
    'beef bowl': {'japanese': '牛丼', 'calories': 716},
    'kinpira-style sauteed burdock': {'japanese': 'きんぴらごぼう', 'calories': 93},
    'rice ball': {'japanese': 'おにぎり', 'calories': 204},
    'pizza toast': {'japanese': 'ピザトースト', 'calories': 282},
    'dipping noodles': {'japanese': 'つけ麵', 'calories': 595},
    'hot dog': {'japanese': 'ホットドッグ', 'calories': 414},
    'french fries': {'japanese': 'フライドポテト', 'calories': 309},
    'mixed rice': {'japanese': '炊き込みご飯', 'calories': 213},
    'goya chanpuru': {'japanese': 'ゴーヤチャンプルー', 'calories': 225},
    'others': {'japanese': 'その他', 'calories': 500},
    'beverage': {'japanese': '飲み物', 'calories': 0},
}
